---
image:
  repository: romanowalex/echo-client
  tag: v3.0

profile: k8s # k8s-load-balancer
ports:
  internal: 8180

# serviceAccountName: spring

environments:
  - name: ECHO_SERVER_URL
    value: http://echo-server.default.svc.cluster.local:8080

ingress:
  enabled: true
  domain: local

resources:
  requests:
    cpu: 0.5
    memory: 1024Mi
  limits:
    cpu: 1
    memory: 1024Mi
